# SwiftLint Configuration for IWBH Project

# Disabled Rules
disabled_rules:
  - trailing_whitespace
  - file_length
  - function_body_length
  - type_body_length
  - cyclomatic_complexity
  - large_tuple
  - todo
  - force_cast
  - force_try

# Opt-in Rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - comment_spacing
  - computed_accessors_order
  - control_statement
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - for_where
  - function_default_parameter_at_end
  - identical_operands
  - joined_default_parameter
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - switch_case_alignment
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
  - valid_ibinspectable
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Included paths
included:
  - ios-app/IWBH
  - ios-app/IWBHTests
  - ios-app/IWBHUITests
  - ios-app/TrackerWidgetExtension

# Excluded paths
excluded:
  - ios-app/IWBH.xcodeproj
  - ios-app/IWBH/Assets.xcassets
  - backend
  - docs
  - scripts
  - Pods
  - Carthage
  - .build

# Configurable Rules
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1200

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - url
    - URL
    - db
    - ok
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 40
    error: 50

# Custom Rules
custom_rules:
  comments_space:
    name: "Space After Comment"
    regex: '(^ *//\w+)'
    message: "There should be a space after //"
    severity: warning

  empty_first_line:
    name: "Empty First Line"
    regex: '(^[ a-zA-Z ]*(?:protocol|extension|class|struct) (?!(?:var|let))[ a-zA-Z:]*\{\n *\S+)'
    message: "There should be an empty line after a declaration"
    severity: warning

# Reporter
reporter: "xcode"
